SDKMACHINE="x86_64-mingw32"
# zip is not used, as if gets unpacked on host machine symlinks are lost,
# causing `as.exe` not being found when trying to compile example project.
# This issue is not present when unpacking tar.xz file
SDK_ARCHIVE_TYPE="tar.xz"