DISTRO_NAME = "Leopard (KP Labs)"
DISTRO_VERSION := "build-${@bb.process.run('git rev-parse HEAD')[0].strip()}"
DISTRO_FEATURES:remove = "alsa bluetooth wifi nfc x11 pulseaudio"
SDK_NAME = "yocto_sdk_${SDK_OS}"
TOOLCHAIN_OUTPUTNAME="${MACHINE}-${SDK_NAME}"

INIT_MANAGER = "systemd"

# apply no suffix to tmp build directory
TCLIBCAPPEND := ""
